maslow:
  build: ../maslow-standalone
  command: bin/rails server -e development --port 3000 --binding 0.0.0.0
  volumes:
    - ../maslow-standalone:/code
  links:
    - postgres
  ports:
    - "3000:3000"
  environment:
    INSTANCE_NAME: maslow-docker
    MASLOW_HOST: cgt-maslow.local
postgres:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: maslow
    POSTGRES_USER: maslow
cgt:
  build: ../cgt
  command: ./docker.sh 
  volumes:
    - ../cgt:/code
  ports:
   - "3001:3001"
cgtprototypes:
  build: ../cgt_prototypes
  command: ./docker.sh 
  volumes:
    - ../cgt_prototypes:/code
  ports:
   - "3002:3002"
