maslow:
  build: apps/maslow-standalone
  command: ./docker.sh 
  volumes:
    - apps/maslow-standalone:/code
  links:
    - postgres
  ports:
    - "3000:3000"
  environment:
    INSTANCE_NAME: maslow-docker
    MASLOW_HOST: cgt-maslow.local
postgres:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: maslow
    POSTGRES_USER: maslow
home:
  build: apps/home
  command: ./docker.sh 
  volumes:
    - apps/home:/code
  ports:
   - "3001:3001"
prototypes:
  build: apps/prototypes
  command: python manage.py server
  links:
    - people
    - locations
  environment:
    APPLICATION_ENV: dev
    PORT: 3003
    BASIC_AUTH_PASSWORD: __BASIC_AUTH_PASSWORD__
    BASIC_AUTH_USERNAME: __BASIC_AUTH_USERNAME__
    BASIC_AUTH_FORCE: __BASIC_AUTH_FORCE__
    LOCATIONS_FRONTEND: locations.xgs.local
  volumes:
    - apps/prototypes:/code
  ports:
    - "3003:3003"
people:
  build: apps/people
  command: python manage.py server
  environment:
    APPLICATION_ENV: dev
    PORT: 3004
    DATABASE_URL: "postgres://prototypes:prototypes@db:5432/prototypes"
    TWILIO_ACCOUNT_ID: __TWILIO_ACCOUNT_ID__
    TWILIO_AUTH_TOKEN: __TWILIO_AUTH_TOKEN__
    TWILIO_PHONE_NUMBER: __TWILIO_PHONE_NUMBER__
    MAIL_SERVER: __MAIL_SERVER__
    MAIL_PORT: __MAIL_PORT__
    MAIL_USERNAME: __MAIL_USERNAME__
    MAIL_PASSWORD: __MAIL_PASSWORD__
    MAIL_USE_TLS: __MAIL_USE_TLS__
    MAIL_USE_SSL: __MAIL_USE_SSL__
  links:
    - db
  volumes:
    - apps/people:/code
  ports:
    - "3004:3004"
db:
  build: apps/db
  environment:
    POSTGRES_PASSWORD: prototypes
    POSTGRES_USER: prototypes
    POSTGRES_DB_MAIN: prototypes
locations:
  build: apps/locations
  environment:
    MODE: dev
    SETTINGS: config.DockerConfig
    PORT: 8001
    SCHOOL_REGISTER: http://school.openregister.org
    ADDRESS_REGISTER: http://address.openregister.org
    POSTCODE_REGISTER: http://postcode.openregister.org
    POSTTOWN_REGISTER: http://post-town.openregister.org
    REGISTER_DOMAIN: openregister.org
  ports:
    - "8001:8001"
  volumes:
    - apps/locations:/usr/src/app
