maslow:
  build: apps/maslow-standalone
  command: ./docker.sh 
  volumes:
    - apps/maslow-standalone:/code
  links:
    - postgres
  ports:
    - "3000:3000"
  environment:
    INSTANCE_NAME: maslow-docker
    MASLOW_HOST: cgt-maslow.local
postgres:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: maslow
    POSTGRES_USER: maslow
cgt:
  build: apps/cgt
  command: ./docker.sh 
  volumes:
    - apps/cgt:/code
  ports:
   - "3001:3001"
xgsprototypes:
  build: apps/xgs_prototypes
  command: python manage.py server
  links:
    - people
  environment:
    APPLICATION_ENV: dev
    PORT: 3003
    BASIC_AUTH_PASSWORD: %BASIC_AUTH_PASSWORD%
    BASIC_AUTH_USERNAME: %BASIC_AUTH_USERNAME%
    BASIC_AUTH_FORCE: True
  volumes:
    - apps/xgs_prototypes:/code
  ports:
    - "3003:3003"
people:
  build: apps/people
  command: python manage.py server
  environment:
    APPLICATION_ENV: dev
    PORT: 3004
    DATABASE_URL: "postgres://prototypes:prototypes@db:5432/prototypes"
    TWILIO_ACCOUNT_ID: %TWILIO_ACCOUNT_ID%
    TWILIO_AUTH_TOKEN: %TWILIO_AUTH_TOKEN%
    TWILIO_PHONE_NUMBER: %TWILIO_PHONE_NUMBER%
    MAIL_SERVER: %MAIL_SERVER%
    MAIL_PORT: %MAIL_PORT%
    MAIL_USERNAME: %MAIL_USERNAME%
    MAIL_PASSWORD: %MAIL_PASSWORD%
    MAIL_USE_TLS: %MAIL_USE_TLS%
    MAIL_USE_SSL: %MAIL_USE_SSL%
  links:
    - db
  volumes:
    - apps/people:/code
  ports:
    - "3004:3004"
db:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: prototypes
    POSTGRES_USER: prototypes
    POSTGRES_DB_MAIN: prototypes
