maslow:
  build: apps/maslow-standalone
  command: ./docker.sh 
  volumes:
    - apps/maslow-standalone:/code
  links:
    - postgres
  ports:
    - "3000:3000"
  environment:
    INSTANCE_NAME: maslow-docker
    MASLOW_HOST: cgt-maslow.local
postgres:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: maslow
    POSTGRES_USER: maslow
cgt:
  build: apps/cgt
  command: ./docker.sh 
  volumes:
    - apps/cgt:/code
  ports:
   - "3001:3001"
cgtprototypes:
  build: apps/cgt_prototypes
  command: ./docker.sh 
  volumes:
    - apps/cgt_prototypes:/code
  ports:
   - "3002:3002"
xgsprototypes:
  build: apps/xgs_prototypes
  command: python manage.py server
  environment:
    APPLICATION_ENV: dev
    PORT: 3003
  volumes:
    - apps/xgs_prototypes:/code
  ports:
    - "3003:3003"
people:
  build: apps/people
  command: python manage.py server
  environment:
    APPLICATION_ENV: dev
    PORT: 3004
    DATABASE_URI: "postgres://prototypes:prototypes@db:5432/prototypes"
  links:
    - db
  volumes:
    - apps/people:/code
  ports:
    - "3004:3004"
db:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: prototypes
    POSTGRES_USER: prototypes
    POSTGRES_DB_MAIN: prototypes
